/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2026-03-12 17:22:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/VIT%20-%20PROJECT/CompusConnect/apache-tomcat-9.0.96/webapps/CampusConnect/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1771873523411L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login - CampusConnect</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"login-page\">\r\n");
      out.write("    <div class=\"login-wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- ═══════════════════════════════════\r\n");
      out.write("             LEFT: Branding / Illustration Panel\r\n");
      out.write("             ═══════════════════════════════════ -->\r\n");
      out.write("        <div class=\"login-left\">\r\n");
      out.write("            <div class=\"login-branding\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Logo -->\r\n");
      out.write("                <div class=\"login-logo\">\r\n");
      out.write("                    <span>🎓</span>\r\n");
      out.write("                    <h1>CampusConnect</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Illustration with floating cards -->\r\n");
      out.write("                <div class=\"login-illustration\">\r\n");
      out.write("                    <div class=\"illus-central\">\r\n");
      out.write("                        <div class=\"illus-circle\">\r\n");
      out.write("                            <span class=\"illus-icon\">🎓</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Floating stat cards -->\r\n");
      out.write("                    <div class=\"float-card float-card-1\">\r\n");
      out.write("                        <span class=\"fc-icon\">👥</span>\r\n");
      out.write("                        <div class=\"fc-text\">\r\n");
      out.write("                            <span class=\"fc-num\">2,400+</span>\r\n");
      out.write("                            <span class=\"fc-label\">Students</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"float-card float-card-2\">\r\n");
      out.write("                        <span class=\"fc-icon\">🏫</span>\r\n");
      out.write("                        <div class=\"fc-text\">\r\n");
      out.write("                            <span class=\"fc-num\">120+</span>\r\n");
      out.write("                            <span class=\"fc-label\">Colleges</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"float-card float-card-3\">\r\n");
      out.write("                        <span class=\"fc-icon\">🤝</span>\r\n");
      out.write("                        <div class=\"fc-text\">\r\n");
      out.write("                            <span class=\"fc-num\">98%</span>\r\n");
      out.write("                            <span class=\"fc-label\">Match Rate</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Decorative ring -->\r\n");
      out.write("                    <div class=\"illus-ring illus-ring-1\"></div>\r\n");
      out.write("                    <div class=\"illus-ring illus-ring-2\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Hero text -->\r\n");
      out.write("                <div class=\"login-hero-text\">\r\n");
      out.write("                    <h2>Find Your College Partner</h2>\r\n");
      out.write("                    <p>Connect with students from your campus.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Feature pills -->\r\n");
      out.write("                <div class=\"login-features\">\r\n");
      out.write("                    <span class=\"lf-pill\">📍 Location-based matching</span>\r\n");
      out.write("                    <span class=\"lf-pill\">🔒 Secure &amp; Private</span>\r\n");
      out.write("                    <span class=\"lf-pill\">⚡ Instant Connect</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ═══════════════════════════════════\r\n");
      out.write("             RIGHT: Login Form Panel\r\n");
      out.write("             ═══════════════════════════════════ -->\r\n");
      out.write("        <div class=\"login-right\">\r\n");
      out.write("            <div class=\"login-form-card fade-in\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"lfc-header\">\r\n");
      out.write("                    <h2>Welcome to CampusConnect</h2>\r\n");
      out.write("                    <p>Enter your credentials to access your account</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Success Message -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Error Message -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Login Form -->\r\n");
      out.write("                <form action=\"login\" method=\"post\" class=\"lfc-form\" id=\"loginForm\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Email -->\r\n");
      out.write("                    <div class=\"lfc-field\">\r\n");
      out.write("                        <label for=\"email\">Email Address</label>\r\n");
      out.write("                        <div class=\"lfc-input-wrap\">\r\n");
      out.write("                            <svg class=\"lfc-input-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                <path d=\"M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z\"/>\r\n");
      out.write("                                <polyline points=\"22,6 12,13 2,6\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            <input\r\n");
      out.write("                                type=\"email\"\r\n");
      out.write("                                id=\"email\"\r\n");
      out.write("                                name=\"email\"\r\n");
      out.write("                                placeholder=\"Enter your email address\"\r\n");
      out.write("                                value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                required\r\n");
      out.write("                                autocomplete=\"email\"\r\n");
      out.write("                            >\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Password -->\r\n");
      out.write("                    <div class=\"lfc-field\">\r\n");
      out.write("                        <label for=\"password\">Password</label>\r\n");
      out.write("                        <div class=\"lfc-input-wrap\">\r\n");
      out.write("                            <svg class=\"lfc-input-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                <rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\" ry=\"2\"/>\r\n");
      out.write("                                <path d=\"M7 11V7a5 5 0 0 1 10 0v4\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            <input\r\n");
      out.write("                                type=\"password\"\r\n");
      out.write("                                id=\"password\"\r\n");
      out.write("                                name=\"password\"\r\n");
      out.write("                                placeholder=\"Enter your password\"\r\n");
      out.write("                                required\r\n");
      out.write("                                autocomplete=\"current-password\"\r\n");
      out.write("                            >\r\n");
      out.write("                            <button type=\"button\" class=\"lfc-eye-btn\" onclick=\"toggleLoginPassword()\" aria-label=\"Toggle password visibility\">\r\n");
      out.write("                                <svg id=\"lfc-eye-open\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                    <path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/>\r\n");
      out.write("                                    <circle cx=\"12\" cy=\"12\" r=\"3\"/>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <svg id=\"lfc-eye-closed\" style=\"display:none\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                    <path d=\"M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19M1 1l22 22\"/>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Remember me + Forgot password -->\r\n");
      out.write("                    <div class=\"lfc-options\">\r\n");
      out.write("                        <label class=\"lfc-remember\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"rememberMe\" id=\"rememberMe\">\r\n");
      out.write("                            <span class=\"lfc-checkmark\"></span>\r\n");
      out.write("                            <span>Remember me</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <a href=\"#\" class=\"lfc-forgot\">Forgot password?</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Submit -->\r\n");
      out.write("                    <button type=\"submit\" class=\"lfc-submit-btn\">\r\n");
      out.write("                        Login\r\n");
      out.write("                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\">\r\n");
      out.write("                            <line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"/>\r\n");
      out.write("                            <polyline points=\"12 5 19 12 12 19\"/>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <!-- Register link -->\r\n");
      out.write("                <div class=\"lfc-footer\">\r\n");
      out.write("                    <p>Not registered yet? <a href=\"register\" class=\"lfc-link\">Create an account</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function toggleLoginPassword() {\r\n");
      out.write("            var input     = document.getElementById('password');\r\n");
      out.write("            var eyeOpen   = document.getElementById('lfc-eye-open');\r\n");
      out.write("            var eyeClosed = document.getElementById('lfc-eye-closed');\r\n");
      out.write("            if (input.type === 'password') {\r\n");
      out.write("                input.type = 'text';\r\n");
      out.write("                eyeOpen.style.display   = 'none';\r\n");
      out.write("                eyeClosed.style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("                input.type = 'password';\r\n");
      out.write("                eyeOpen.style.display   = 'block';\r\n");
      out.write("                eyeClosed.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /login.jsp(93,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.successMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    <div class=\"alert alert-success\">\r\n");
        out.write("                        <span class=\"alert-icon\">✓</span>\r\n");
        out.write("                        ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.successMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                    </div>\r\n");
        out.write("                    ");
        if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /login.jsp(98,20) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f0.setVar("successMessage");
    // /login.jsp(98,20) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f0.setScope("session");
    int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
    if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /login.jsp(102,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    <div class=\"alert alert-error\">\r\n");
        out.write("                        <span class=\"alert-icon\">!</span>\r\n");
        out.write("                        ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                    </div>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager());
    return false;
  }
}
